// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/infra/txv3/tx.proto

package txv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction_Op int32

const (
	Transaction_UNKNOWN Transaction_Op = 0
	Transaction_PUT     Transaction_Op = 1
	Transaction_PATCH   Transaction_Op = 2
	Transaction_DELETE  Transaction_Op = 3
	Transaction_MERGE   Transaction_Op = 4
)

// Enum value maps for Transaction_Op.
var (
	Transaction_Op_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUT",
		2: "PATCH",
		3: "DELETE",
		4: "MERGE",
	}
	Transaction_Op_value = map[string]int32{
		"UNKNOWN": 0,
		"PUT":     1,
		"PATCH":   2,
		"DELETE":  3,
		"MERGE":   4,
	}
)

func (x Transaction_Op) Enum() *Transaction_Op {
	p := new(Transaction_Op)
	*p = x
	return p
}

func (x Transaction_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_infra_txv3_tx_proto_enumTypes[0].Descriptor()
}

func (Transaction_Op) Type() protoreflect.EnumType {
	return &file_internal_infra_txv3_tx_proto_enumTypes[0]
}

func (x Transaction_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_Op.Descriptor instead.
func (Transaction_Op) EnumDescriptor() ([]byte, []int) {
	return file_internal_infra_txv3_tx_proto_rawDescGZIP(), []int{0, 0}
}

type Transaction struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TxId       string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Collection string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	DocId      string                 `protobuf:"bytes,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Op         Transaction_Op         `protobuf:"varint,5,opt,name=op,proto3,enum=ledgerdb.v3.Transaction_Op" json:"op,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Transaction_Snapshot
	//	*Transaction_Patch
	Payload       isTransaction_Payload `protobuf_oneof:"payload"`
	ParentHash    string                `protobuf:"bytes,8,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	SchemaVersion string                `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_infra_txv3_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_txv3_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_infra_txv3_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Transaction) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Transaction) GetOp() Transaction_Op {
	if x != nil {
		return x.Op
	}
	return Transaction_UNKNOWN
}

func (x *Transaction) GetPayload() isTransaction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transaction) GetSnapshot() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Transaction) GetPatch() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Transaction_Patch); ok {
			return x.Patch
		}
	}
	return nil
}

func (x *Transaction) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *Transaction) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type isTransaction_Payload interface {
	isTransaction_Payload()
}

type Transaction_Snapshot struct {
	Snapshot []byte `protobuf:"bytes,6,opt,name=snapshot,proto3,oneof"`
}

type Transaction_Patch struct {
	Patch []byte `protobuf:"bytes,7,opt,name=patch,proto3,oneof"`
}

func (*Transaction_Snapshot) isTransaction_Payload() {}

func (*Transaction_Patch) isTransaction_Payload() {}

var File_internal_infra_txv3_tx_proto protoreflect.FileDescriptor

const file_internal_infra_txv3_tx_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/infra/txv3/tx.proto\x12\vledgerdb.v3\"\xeb\x02\n" +
	"\vTransaction\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x15\n" +
	"\x06doc_id\x18\x04 \x01(\tR\x05docId\x12+\n" +
	"\x02op\x18\x05 \x01(\x0e2\x1b.ledgerdb.v3.Transaction.OpR\x02op\x12\x1c\n" +
	"\bsnapshot\x18\x06 \x01(\fH\x00R\bsnapshot\x12\x16\n" +
	"\x05patch\x18\a \x01(\fH\x00R\x05patch\x12\x1f\n" +
	"\vparent_hash\x18\b \x01(\tR\n" +
	"parentHash\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\"<\n" +
	"\x02Op\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\t\n" +
	"\x05PATCH\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\t\n" +
	"\x05MERGE\x10\x04B\t\n" +
	"\apayloadB:Z8github.com/codecompany/ledgerdb/internal/infra/txv3;txv3b\x06proto3"

var (
	file_internal_infra_txv3_tx_proto_rawDescOnce sync.Once
	file_internal_infra_txv3_tx_proto_rawDescData []byte
)

func file_internal_infra_txv3_tx_proto_rawDescGZIP() []byte {
	file_internal_infra_txv3_tx_proto_rawDescOnce.Do(func() {
		file_internal_infra_txv3_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_txv3_tx_proto_rawDesc), len(file_internal_infra_txv3_tx_proto_rawDesc)))
	})
	return file_internal_infra_txv3_tx_proto_rawDescData
}

var file_internal_infra_txv3_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_infra_txv3_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_infra_txv3_tx_proto_goTypes = []any{
	(Transaction_Op)(0), // 0: ledgerdb.v3.Transaction.Op
	(*Transaction)(nil), // 1: ledgerdb.v3.Transaction
}
var file_internal_infra_txv3_tx_proto_depIdxs = []int32{
	0, // 0: ledgerdb.v3.Transaction.op:type_name -> ledgerdb.v3.Transaction.Op
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_txv3_tx_proto_init() }
func file_internal_infra_txv3_tx_proto_init() {
	if File_internal_infra_txv3_tx_proto != nil {
		return
	}
	file_internal_infra_txv3_tx_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_Snapshot)(nil),
		(*Transaction_Patch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_txv3_tx_proto_rawDesc), len(file_internal_infra_txv3_tx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infra_txv3_tx_proto_goTypes,
		DependencyIndexes: file_internal_infra_txv3_tx_proto_depIdxs,
		EnumInfos:         file_internal_infra_txv3_tx_proto_enumTypes,
		MessageInfos:      file_internal_infra_txv3_tx_proto_msgTypes,
	}.Build()
	File_internal_infra_txv3_tx_proto = out.File
	file_internal_infra_txv3_tx_proto_goTypes = nil
	file_internal_infra_txv3_tx_proto_depIdxs = nil
}
